RUN = "mbgru_token"
LOG_PATH = RUN + ".log"

MANUAL_SEED = 42

DATA_PATH = "/scratch/rabin/token_embedding/data/"
DATASET_NAME = "java-large"
ONLY_IDENTIFIER = True
TOKEN_PATH = DATA_PATH + "Token/" + DATASET_NAME + "_" + str(ONLY_IDENTIFIER) + ".jsonl"

PAD_TOKEN, UNK_TOKEN = '<PAD>', '<UNK>'
PAD_INDEX, UNK_INDEX = 0, 1

BATCH_SIZE = 32
EPOCH = 1000
PATIENCE = 10

OUTPUT_DIM = 11
LEARNING_RATE = 1e-2
MOMENTUM = 0.99
HIDDEN_LAYER = 2
HIDDEN_DIM = 128
DROPOUT_RATIO = 0.3

CHECKPOINT = RUN + ".model"
